export const products = [
  {
    id: "red-floral-art",
    name: "Red Floral Art",
    price: 950,
    currency: "PKR",
    description: "Bold crimson coffin nails with hand-painted white florals & polka dot accents. A statement set for the maximalist.",
    image: "/images/whatsapp_3.jpeg",
    shape: "Coffin",
    color: "Red",
    badge: "BEST SELLER",
    reviews: 42,
    rating: 5,
    cardClass: "card-pink"
  },
  {
    id: "blush-peach-almond",
    name: "Blush Peach Almond",
    price: 920,
    currency: "PKR",
    description: "Soft, glossy peach almond nails — the definition of clean girl aesthetic. Buttery finish, zero damage.",
    image: "/images/whatsapp_5.jpeg",
    shape: "Almond",
    color: "Nude",
    badge: "",
    reviews: 38,
    rating: 5,
    cardClass: "card-mint"
  },
  {
    id: "rose-gold-shimmer",
    name: "Rose Gold Shimmer",
    price: 940,
    currency: "PKR",
    description: "Alluring rose gold sparkle finish on almond nails. Catches every light with a dreamy metallic glow.",
    image: "/images/whatsapp_6.jpeg",
    shape: "Almond",
    color: "Metallic",
    badge: "HOT",
    reviews: 55,
    rating: 5,
    cardClass: "card-lavender"
  },
  {
    id: "cherry-red-stiletto",
    name: "Cherry Red Stiletto",
    price: 950,
    currency: "PKR",
    description: "Deep, rich cherry red stiletto nails. Glossy, fierce, and ultra-dramatic — wear your confidence.",
    image: "/images/whatsapp_9.jpeg",
    shape: "Stiletto",
    color: "Red",
    badge: "TRENDING",
    reviews: 61,
    rating: 5,
    cardClass: "card-pink"
  },
  {
    id: "bubblegum-pink-almond",
    name: "Bubblegum Pink Almond",
    price: 920,
    currency: "PKR",
    description: "Sheer bubblegum pink almond nails with a translucent finish. Cute, feminine, and effortlessly chic.",
    image: "/images/whatsapp_13.jpeg",
    shape: "Almond",
    color: "Pink",
    badge: "",
    reviews: 29,
    rating: 4,
    cardClass: "card-mint"
  },
  {
    id: "nude-mauve-stiletto",
    name: "Nude Mauve Stiletto",
    price: 930,
    currency: "PKR",
    description: "Sophisticated nude mauve stiletto nails — elongating, flattering, and perpetually on-trend.",
    image: "/images/whatsapp_14.jpeg",
    shape: "Stiletto",
    color: "Nude",
    badge: "",
    reviews: 33,
    rating: 4,
    cardClass: "card-lavender"
  },
  {
    id: "pearl-pink-polka-dot",
    name: "Pearl Pink Polka Dot",
    price: 940,
    currency: "PKR",
    description: "Creamy pearl white almond nails adorned with raised 3D pink polka dots. Textured, playful & unique.",
    image: "/images/whatsapp_17.jpeg",
    shape: "Almond",
    color: "Pink",
    badge: "LIMITED",
    reviews: 21,
    rating: 5,
    cardClass: "card-yellow"
  },
  {
    id: "coral-blush-ombre",
    name: "Coral Blush Ombre",
    price: 940,
    currency: "PKR",
    description: "Ethereal coral-to-blush aura ombre stiletto nails. Dreamy gradient that looks airbrushed to perfection.",
    image: "/images/whatsapp_19.jpeg",
    shape: "Stiletto",
    color: "Pink",
    badge: "NEW",
    reviews: 18,
    rating: 5,
    cardClass: "card-pink"
  },
  {
    id: "terracotta-glitter-almond",
    name: "Terracotta Glitter",
    price: 950,
    currency: "PKR",
    description: "Warm nude terracotta almond nails with a sweeping silver glitter diagonal. Earthy meets glam.",
    image: "/images/whatsapp_21.jpeg",
    shape: "Almond",
    color: "Metallic",
    badge: "",
    reviews: 26,
    rating: 5,
    cardClass: "card-yellow"
  },
  {
    id: "aqua-teal-shimmer",
    name: "Aqua Teal Shimmer",
    price: 950,
    currency: "PKR",
    description: "Stunning aqua teal stiletto nails with a pearl shimmer finish. Bold color, impossible to ignore.",
    image: "/images/whatsapp_26.jpeg",
    shape: "Stiletto",
    color: "Blue",
    badge: "EXCLUSIVE",
    reviews: 14,
    rating: 5,
    cardClass: "card-mint"
  }
];
